export default {
  getForwardTestingFields(currency) {
    return {
      accountBalance: {
        id: 1,
        label: "Account balance:",
        value: "",
        field: "input",
        fixedHeight: "26px",
        key: "accountBalance",
        hasPrefix: true,
        prefixText: currency.symbol,
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
        nextFieldFocus: "totalTrades",
      },
      baseCurrency: {
        id: 2,
        label: "Currency:",
        value: currency.text,
        field: "dropdown",
        key: "baseCurrency",
        items: [
          { id: 1, text: "USD" },
          { id: 2, text: "EUR" },
          { id: 3, text: "GBP" },
          { id: 4, text: "JPY" },
          { id: 5, text: "CAD" },
          { id: 6, text: "AUD" },
          { id: 7, text: "CHF" },
          { id: 8, text: "NZD" },
        ],
        disabled: false,
        visible: true,
        warning: false,
        fixedHeight: true,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 25,
        minimum: 1,
      },
      totalTrades: {
        id: 3,
        label: "Total trades:",
        value: "100",
        field: "input",
        fixedHeight: "26px",
        key: "totalTrades",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 4,
        minimum: 1,
        tooltip: "",
        nextFieldFocus: "accountBalance",
      },
      winRate: {
        id: 4,
        label: "Win rate:",
        value: 50,
        field: "slider-advanced",
        key: "winRate",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        sliderMaximum: 100,
        sliderMinimum: 1,
        sliderStep: 0.1,
        labelText: "%",
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        bottomLine: true,
        tooltip: "",
      },
      reward: {
        id: 5,
        label: "Trade reward:",
        value: 4,
        field: "slider-advanced",
        key: "reward",
        disabled: false,
        visible: true,
        warning: false,
        hasPrefix: true,
        prefixText: currency.symbol,
        isTradingMode: false,
        rightColumn: false,
        sliderMaximum: 100,
        sliderMinimum: 1,
        sliderStep: 0.1,
        labelText: "%",
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
      risk: {
        id: 6,
        label: "Trade risk:",
        value: 1,
        field: "slider-advanced",
        key: "risk",
        disabled: false,
        visible: true,
        warning: false,
        hasPrefix: true,
        prefixText: currency.symbol,
        isTradingMode: false,
        rightColumn: false,
        sliderMaximum: 100,
        sliderMinimum: 1,
        sliderStep: 0.1,
        labelText: "%",
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        bottomLine: true,
        tooltip: "",
      },
      fixedReward: {
        id: 7,
        label: "Reward in:",
        value: "%",
        items: [
          { id: 1, text: "%" },
          { id: 2, text: currency.symbol },
        ],
        field: "select-options",
        key: "fixedReward",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
      fixedRisk: {
        id: 8,
        label: "Risk in:",
        value: "%",
        items: [
          { id: 1, text: "%" },
          { id: 2, text: currency.symbol },
        ],
        field: "select-options",
        key: "fixedRisk",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
      winRateOnOdds: {
        id: 9,
        label: "Win rate on odds:",
        value: false,
        field: "switch",
        key: "winRateOnOdds",
        hasHelpButton: true,
        helpText:
          "If this feature is turned off, it will divide the total trades based on the win rate. For example, if the win rate is 50%, out of 100 trades, there would be 50 losses and 50 winners. On the other hand, if this feature is turned on, each trade will be classified as a loss or a win based on the win rate odds. This will introduce random results for each calculation. If you desire consistent results, it is recommended to keep the feature turned off. However, if you prefer more flexible and variable outcomes, you should enable it.",
        disabled: false,
        bootstrapTooltip: true,
        popUpStyleProps: {
          width: 250,
          height: 350,
        },
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
    };
  },
  getBackTestingFields(currency) {
    return {
      accountBalance: {
        id: 1,
        label: "Account balance:",
        value: "",
        field: "input",
        readOnly: false,
        fixedHeight: "26px",
        key: "accountBalance",
        hasPrefix: true,
        prefixText: currency.symbol,
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
        nextFieldFocus: "lossReward",
        bottomLine: true,
      },
      baseCurrency: {
        id: 2,
        label: "Currency:",
        value: currency.text,
        field: "dropdown",
        key: "baseCurrency",
        items: [
          { id: 1, text: "USD" },
          { id: 2, text: "EUR" },
          { id: 3, text: "GBP" },
          { id: 4, text: "JPY" },
          { id: 5, text: "CAD" },
          { id: 6, text: "AUD" },
          { id: 7, text: "CHF" },
          { id: 8, text: "NZD" },
        ],
        disabled: false,
        visible: true,
        warning: false,
        fixedHeight: true,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 25,
        minimum: 1,
      },
      lossReward: {
        id: 3,
        label: "P&L:",
        value: "",
        field: "input",
        fixedHeight: "26px",
        key: "lossReward",
        disabled: false,
        hasPrefix: true,
        prefixText: currency.symbol,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        sliderMaximum: 100,
        sliderMinimum: 1,
        sliderStep: 0.1,
        labelText: "%",
        showLabel: false,
        type: "number",
        maxLength: 6,
        minimum: 1,
        tooltip: "",
        nextFieldFocus: "accountBalance",
      },
      winOrLoss: {
        id: 4,
        label: "Result:",
        value: "Win",
        items: [
          { id: 1, text: "Win" },
          { id: 2, text: "Loss" },
        ],
        field: "select-options",
        key: "winOrLoss",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
      fixedRiskReward: {
        id: 5,
        label: "TP in:",
        value: currency.symbol,
        items: [
          { id: 1, text: "%" },
          { id: 2, text: currency.symbol },
        ],
        field: "select-options",
        key: "fixedRiskReward",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
      saveBacktest: {
        id: 6,
        label: "Save backtest:",
        value: true,
        field: "switch",
        key: "saveBacktest",
        disabled: false,
        visible: true,
        warning: false,
        isTradingMode: false,
        rightColumn: false,
        showLabel: false,
        type: "number",
        maxLength: 8,
        minimum: 1,
        tooltip: "",
      },
    };
  },
  getDataTableFields(currency, formatNumber) {
    return {
      thead: [
        {
          order: 1,
          value: "Trade",
          columnId: "id",
          class: "bold",
          key: "id",
        },
        {
          order: 2,
          value: "Balance",
          align: "left",
          columnId: "oldAccountBalance",
          class: "bold",
          key: "balance",
        },
        {
          order: 3,
          value: "P & L",
          align: "left",
          sort: "asc",
          columnId: "pnl",
          class: "bold",
          key: "pnl",
        },
        {
          order: 4,
          value: "New balance",
          align: "left",
          columnId: "accountBalance",
          class: "bold",
          key: "accountBalance",
        },
        {
          order: 5,
          value: "Result",
          align: "left",
          sort: "asc",
          columnId: "state",
          class: "bold",
          key: "state",
        },
        {
          order: 6,
          value: "",
          field: "Action",
          key: "action",
        },
      ],
      tbody: [
        {
          order: 1,
          field: "id",
          width: 200,
          key: "id",
          class: (data) => {
            return "verticle-align zoom";
          },
        },
        {
          order: 2,
          field: "oldAccountBalance",
          width: 350,
          fn: (data) => {
            const price = formatNumber(data.oldAccountBalance, true, true);
            if (price === "Error") return "Error";
            return `${currency.symbol}${price}`;
          },
          class: (data) => {
            return "verticle-align zoom";
          },
          key: "contract",
        },
        {
          order: 3,
          field: "pnl",
          width: 10,
          fn: (data) => {
            const price = formatNumber(Math.abs(data.pnl), true, true);
            if (price === "Error") return "Error";
            return `${currency.symbol}${price}`;
          },
          class: (data) => {
            const state = data.pnl > 0 ? "is-positive" : "is-negative";
            return `verticle-align zoom ${state}`;
          },
          key: "pnl",
        },
        {
          order: 4,
          field: "accountBalance",
          width: 300,
          fn: (data) => {
            const price = formatNumber(data.accountBalance, true, true);
            if (price === "Error") return "Error";
            return `${currency.symbol}${price}`;
          },
          class: (data) => {
            return "verticle-align zoom";
          },
          key: "accountBalance",
        },
        {
          order: 5,
          field: "state",
          width: 10,
          fn: (data) => {
            return data.state.charAt(0).toUpperCase() + data.state.slice(1);
          },
          class: (data) => {
            const state = data.state === "win" ? "is-positive" : "is-negative";
            return `verticle-align zoom ${state}`;
          },
          key: "state",
        },
        {
          order: 6,
          slot: "actions",
          class: "verticle-align action",
          field: "Action",
          width: 50,
          key: "action",
        },
      ],
    };
  },
};
